import {
  autoGeneratedHashKey,
  attribute,
  table,
} from '@aws/dynamodb-data-mapper-annotations';

import { dynamoDBConfig } from '../config/aws';

@table(dynamoDBConfig.locationTableName)
export class Location {
  @autoGeneratedHashKey()
  id?: string;

  @attribute()
  latitude: string;

  @attribute()
  longitude: string;

  @attribute()
  address: string;
}
